# Generated by Django 5.1.1 on 2024-10-20 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tg_chat_id',
            field=models.CharField(blank=True, help_text='Укажите id чата в Телеграмм', max_length=255, null=True, verbose_name='id чата в Телеграмм'),
        ),
    ]
