# Generated by Django 5.1.1 on 2024-09-23 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Укажите название породы', max_length=100, null=True, verbose_name='Название породы')),
                ('description', models.TextField(blank=True, help_text='Укажите описание породы', null=True, verbose_name='Описание породы')),
            ],
            options={
                'verbose_name': 'Порода',
                'verbose_name_plural': 'Породы',
            },
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Укажите кличку собаки', max_length=100, null=True, verbose_name='Кличка')),
                ('photo', models.ImageField(blank=True, help_text='Загрузите фото собаки', null=True, upload_to='dogs/photo', verbose_name='Фото')),
                ('date_born', models.DateField(blank=True, help_text='Укажите дату рождения', null=True, verbose_name='Дата рождения')),
                ('breed', models.ForeignKey(blank=True, help_text='Выберите породу', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dogs.breed', verbose_name='Порода')),
            ],
            options={
                'verbose_name': 'Собака',
                'verbose_name_plural': 'Собаки',
            },
        ),
    ]
